apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudknowledges
spec: 
  selector:
    matchLable:
      app: cloudknowledges
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnvailable: 1

  template
    metadata:
      label:
        app: cloudknowledges
     spec:
       containers:
       - name: cloudknowledges
         image: nkciam/chungnk:chung-docker-demo
         imagePullPolicy: Always
         port:
         - containerPort: 80
         env:
           - name: PORT
             value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudknowledges
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cloudknowledges             
