apiVersion: apps/v1
kind: Deployment
metadata:
  name: chung-diamond
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chung-diamond
  template:
    metadata:
      labels:
        app: chung-diamond
    spec:
      containers:
        - name: chung-diamond
          image: nkciam/chungnk:chung-docker-demo
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: chung-diamond
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: chung-diamond
